
ALTER TABLE public.terminology_terms 
ADD COLUMN IF NOT EXISTS definition_fr TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS definition_en TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS example_fr TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS example_en TEXT NOT NULL DEFAULT '';
